"""empty message

Revision ID: aa1fe7b5e216
Revises: fa866e0f1c58
Create Date: 2024-07-05 11:57:11.047777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1fe7b5e216'
down_revision = 'fa866e0f1c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cast',
    sa.Column('CastD', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CastName', sa.String(length=100), nullable=True),
    sa.Column('MovieID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MovieID'], ['movie.MovieID'], ),
    sa.PrimaryKeyConstraint('CastD')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cast')
    # ### end Alembic commands ###
