"""empty message

Revision ID: ea84ff0372a7
Revises: 579b1f1e0690
Create Date: 2024-07-03 23:34:14.913462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea84ff0372a7'
down_revision = '579b1f1e0690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MovieTitle', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('MovieImage', sa.String(length=255), nullable=True))
        batch_op.drop_column('Movie')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Movie', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('MovieImage')
        batch_op.drop_column('MovieTitle')

    # ### end Alembic commands ###
