"""empty message

Revision ID: fa866e0f1c58
Revises: ad0981352a5c
Create Date: 2024-07-05 10:47:04.709085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa866e0f1c58'
down_revision = 'ad0981352a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MovieImageSide', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('MovieImageSide')

    # ### end Alembic commands ###
